"""Create tables in dbo schema

Revision ID: 4c4711a50cc7
Revises: 847b2fa54624
Create Date: 2025-09-22 14:05:37.550376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c4711a50cc7'
down_revision: Union[str, Sequence[str], None] = '847b2fa54624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    # schema='dbo',
    if_not_exists=True
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['dbo.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    # schema='dbo',
    if_not_exists=True
    )
    # op.execute("INSERT INTO dbo.users (name) VALUES ('Alice')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("DELETE FROM dbo.users WHERE name = 'Alice'")
    op.execute("DELETE FROM users WHERE name = 'Alice'")
    # op.drop_table('notes', schema='dbo')
    # op.drop_table('users', schema='dbo')
    op.drop_table('notes')
    op.drop_table('users')
    # ### end Alembic commands ###
