"""Add categories foreign key in note model

Revision ID: af1210fcf93e
Revises: 71dbda0edd5d
Create Date: 2025-09-23 14:10:27.300641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1210fcf93e'
down_revision: Union[str, Sequence[str], None] = '71dbda0edd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'categories', ['category_id'], ['id'])
    op.execute("INSERT INTO users (name) VALUES ('Alice')")
    op.execute("INSERT INTO categories (name) VALUES ('Work')")
    op.execute("INSERT INTO categories (name) VALUES ('Personal')")
    op.execute("INSERT INTO categories (name) VALUES ('To Do')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'category_id')
    # ### end Alembic commands ###
